###########################
## Linter GitHub Actions ##
###########################
# https://github.com/github/super-linter

name: Linter

# Controls when the action will run. Triggers the workflow on push or pull request
# events
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # Name the Job
    name: Lint Code Base
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Code
        uses: actions/checkout@v2

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter@v4.0.2
        env:
          # Will parse the entire repository and find all files to validate across all types.
          # NOTE: When set to false, only new or edited files will be parsed for validation.
          VALIDATE_ALL_CODEBASE: false
          # The name of the repository default branch.
          DEFAULT_BRANCH: main
          # Flag to enable or disable the linting process of the Javascript language. (Utilizing: eslint)
          VALIDATE_JAVASCRIPT_ES: true
          # Flag to enable or disable the linting process of the JSON language.
          VALIDATE_JSON: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
